### ISSUE TITLE
Oprava úkolu

### ISSUE THREAD

**Issue by jakubledl** [LucieSt/ukolnicek#1]
Ahoj!

Skvělá práce, funguje to krásně :-) Nemůžu to uznat kvůli jediné věci, a to je to filtrování všech / pouze nesplněných úkolů. Martin na lekci říkal takový obecný princip, že filtrování se typicky dělá přímo na použitém API, spíš než že by se z API stáhlo všechno a pak se to filtrovalo na klientovi. V zadání se píše o tom, jak přímo to API filtrování podporuje (bod g.); tohle je potřeba opravit, jinak je to všechno v pohodě :-)

**Comment by LucieSt** [comment]
Ahoj! Dekuju :) Opravila jsem filtrovani, je to takhle lepsi?

**Comment by jakubledl** [comment]
Ahoj, perfektní 🙂 👍 Dodal bych jen, že v obou případech (zaškrtnuto/nezaškrtnuto) jsou ty adresy na API skoro stejné, takže by se to dalo ještě trochu zjednodušit/sjednotit, ale to už je detail.
